# Generated by Django 4.0.4 on 2022-05-30 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('admit_date', models.DateField()),
                ('course', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('section', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
